// Private helper page (noindex): the daily Instagram kit. Cards and captions
// are generated by scripts/ig-cards.mjs into public/ig/ and read here at
// build time - every generator commit redeploys the site, so this page always
// shows the latest set. Labels are in Russian because this page is the site
// owner's tool, not visitor-facing content.
import fs from "node:fs";
import path from "node:path";
import type { Metadata } from "next";
import CopyButton from "@/components/CopyButton";

export const metadata: Metadata = {
  title: "Instagram-набор",
  robots: { index: false, follow: false },
};

type IgCard = {
  file: string;
  title: string;
  sourceName: string;
  sourceUrl: string;
  category: string;
  caption: string;
};

type IgKit = {
  date: string;
  generatedAt: string;
  cards: IgCard[];
  groupCaption: string;
};

function getKit(): IgKit | null {
  try {
    const raw = fs.readFileSync(path.join(process.cwd(), "public", "ig", "latest.json"), "utf-8");
    return JSON.parse(raw) as IgKit;
  } catch {
    return null;
  }
}

export default function InstagramKitPage() {
  const kit = getKit();

  if (!kit) {
    return (
      <div className="max-w-2xl">
        <h1 className="text-3xl font-extrabold mb-4">Instagram-набор</h1>
        <p className="text-muted">
          Карточки ещё не сгенерированы. Они появятся после первого запуска workflow
          «Instagram Cards» (каждый день в 11:30 UTC, или вручную во вкладке Actions на GitHub).
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="text-3xl font-extrabold mb-2">Instagram-набор · {kit.date}</h1>
        <p className="text-muted max-w-2xl">
          Готовые карточки на сегодня. Публикация за 2 минуты: нажми на карточку, сохрани
          картинку, скопируй подпись кнопкой — и выложи пост в Instagram. Новый набор
          появляется здесь каждый день автоматически.
        </p>
      </div>

      <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
        {kit.cards.map((card, i) => (
          <div
            key={card.file}
            className="rounded-3xl bg-card shadow-[0_2px_12px_rgba(122,98,74,0.08)] overflow-hidden flex flex-col"
          >
            <a href={card.file} target="_blank" rel="noopener noreferrer">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={card.file} alt={card.title} className="w-full" loading="lazy" />
            </a>
            <div className="p-5 flex flex-col gap-3 flex-1">
              <p className="text-sm font-bold">Карточка {i + 1}</p>
              <pre className="text-xs text-muted whitespace-pre-wrap font-sans bg-background rounded-2xl p-3 flex-1">
                {card.caption}
              </pre>
              <div className="flex flex-wrap gap-2">
                <CopyButton text={card.caption} label="Скопировать подпись" />
                <a
                  href={card.file}
                  download
                  className="rounded-full bg-peach text-peach-deep font-bold text-sm px-4 py-2 hover:opacity-90 transition-opacity"
                >
                  Скачать картинку
                </a>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="rounded-3xl bg-card shadow-[0_2px_12px_rgba(122,98,74,0.08)] p-5 max-w-2xl">
        <p className="text-sm font-bold mb-3">
          Общая подпись (если выкладываешь все карточки одной каруселью)
        </p>
        <pre className="text-xs text-muted whitespace-pre-wrap font-sans bg-background rounded-2xl p-3 mb-3">
          {kit.groupCaption}
        </pre>
        <CopyButton text={kit.groupCaption} label="Скопировать общую подпись" />
      </div>
    </div>
  );
}
